services:
  filecoin:
    image: fil-onboarding-report
    build: ./
    env_file: .env
    networks:
      - caddy
    volumes:
      - ~/.config/internetarchive/ia.ini:/root/.config/internetarchive/ia.ini
    labels:
      caddy: ${PROXYHOST}
      caddy.reverse_proxy: "{{upstreams 8501}}"
      caddy.watch: true
networks:
  caddy:
    external: true
